name: Checking all test

on:
  pull_request:
    branches: [ "master"]

jobs: 
  build:
    strategy:
      matrix:
        configuration: [ "Debug", "Release" ]

    runs-on: ubuntu-latest

    env:
      Solution_Name: ExamTestAPI.sln
      Test_Project: ExamTestAPI.Tests.csproj
      SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      SONAR_PROJECT_KEY: ${{ secrets.SONAR_PROJECT_KEY }}
      SONAR_ORG: "luigimonsoft"
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install .NET 
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 8.0.x

      - name: Execute unit test
        run: dotnet test

      - name: install dotnet-coverage
        run: dotnet tool install --global dotnet-coverage

      - name: Install ReportGenerator
        run: dotnet tool install --global dotnet-reportgenerator-globaltool

      - name: Cache SonarQube Cloud packages
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar
          restore-keys: ${{ runner.os }}-sonar

      - name: Cache SonarQube Cloud scanner
        id: cache-sonar-scanner
        uses: actions/cache@v4
        with:
          path: ~\sonar\cache
          key: ${{ runner.os }}-sonar-scanner
          restore-keys: ${{ runner.os }}-sonar-scanner

      - name: Install SonarQube Cloud scanner
        run: dotnet tool install --global dotnet-sonarscanner

      - name: SonarCloud - Begin Analysis
        run: |
          dotnet sonarscanner begin /k:"${{ secrets.SONAR_PROJECT_KEY }}" \
            /o:"${{ env.SONAR_ORG }}" \
            /d:sonar.host.url="https://sonarcloud.io" \
            /d:sonar.token="${{ secrets.SONAR_TOKEN }}" \
            /d:sonar.cs.vscoveragexml.reportsPaths=coverage.xml
      
      - name: Restore dependencies
        run: dotnet restore
        
      - name: Build
        run: dotnet build --no-restore --configuration ${{ matrix.configuration }}

      - name: Run Tests with Coverage
        run: dotnet-coverage collect "dotnet test --no-build --configuration ${{ matrix.configuration }}" -f xml -o "coverage.xml"
             
      - name: SonarCube - SonaCloud -> End
        run: dotnet sonarscanner end /d:sonar.token="${{ secrets.SONAR_TOKEN }}"
        
        
